services:
  webserver:
    depends_on:
      mysql:
        condition: service_healthy
    container_name: webserver
    image: mon-image:latest
    ports:
      - "80:80"
  scripts:
    container_name: scripts
    # image: node-scripts:latest
    build:
      context: .
      dockerfile: scripts.dockerfile
    command: calculator.js
    volumes:
      - scripts-data:/src
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: toto
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 15s
      retries: 3
volumes:
  scripts-data: {}